[package]
name = "rwkday"
authors = ["Vítor Nunes <vitor.sobrinho.nunes@gmail.com"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
rand = "0.8.5"
